openapi: 3.1.0
info:
  title: Connect BCA
  version: 1.0.0
  description: API for generate payment QRIS
servers:
  - url: https://connect-bca-api.glitch.me/api/v1.0
    description: Development server
tags:
  - name: QRIS
    description: Admin and Super Admin related endpoints
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResponseQRISTransfer:
      type: object
      properties:
        qrImage:
          type: string
        expiresAt:
          type: string
    ResponseQRISPay:
      type: object
      properties:
        qrImage:
          type: string
paths:
  /qr/qr-transfer:
    post:
      summary: Generate QRIS Transfer
      tags:
        - QRIS
      security:
        - BearerAuth: []
      parameters:
        - name: mode
          in: query
          required: false
          schema:
            type: string
            enum: [bright, dark]
          description: Default mode is bright
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseQRISTransfer'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Error
  /qr/qr-pay:
    get:
      summary: Generate QRIS Payment
      tags:
        - QRIS
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseQRISPay'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Error