openapi: 3.0.0
info:
  title: Connect BCA
  version: 1.0.0
  description: API for generate payment using QR code
servers:
  - url: https://connect-bca-api.glitch.me/api/v1.0
    description: Development server
tags:
  - name: QRIS
    description: Generate QR code for payment address
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResponseQRTransfer:
      type: object
      properties:
        qrImage:
          type: string
        expiresAt:
          type: number
    ResponseQRPay:
      type: object
      properties:
        qrImage:
          type: string
    ResponseVerifyQR:
      type: object
      oneOf:
        - properties:
            recipient:
              type: object
              properties:
                name:
                  type: string
                accountNumber:
                  type: string
            type:
              type: string
          required:
            - recipient
            - type
        - properties:
            recipient:
              type: object
              properties:
                name:
                  type: string
                accountNumber:
                  type: string
            amount:
              type: object
              properties:
                value:
                  type: number
                currency:
                  type: string
            type:
              type: string
            expiresAt:
              type: number
          required:
            - recipient
            - amount
            - type
            - expiresAt
paths:
  /qr/qr-transfer:
    post:
      summary: Generate QR Transfer
      tags:
        - QR Code
      security:
        - BearerAuth: []
      parameters:
        - name: mode
          in: query
          required: false
          schema:
            type: string
            enum: [bright, dark]
          description: Default mode is bright
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseQRTransfer'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Error
  /qr/qr-pay:
    get:
      summary: Generate QR Payment
      tags:
        - QR Code
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseQRPay'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Error
  /qr/qr-verify:
    post:
      summary: Verify QR Payload
      tags:
        - QR Code
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseVerifyQR'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Error