# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - staging
      
jobs:
  deploy:
    name: connect-bca app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Install dependencies
      run: npm install
    
    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: 
        flyctl deploy --remote-only
